# yml中支持多模块环境配置，用 "---"分开即可
server:
  port: 8180
spring:
  profiles:
    active: dev

logging:
  # 打印的日志级别配置
  level:
    # 指明日志打印范围，不配置会报错
    com.codebear: info
  file:
    # 在当前项目下生成spring boot.log日志，也可指定别的位置，如E:...（一般以配置下面的path为主）
    #name: E:/springboot.log
    # 在当前磁盘的根目录下创建spring文件夹和里面的log文件夹，使用spring.log作为默认文件
    path: /spring/log
  pattern:
    # 在控制台输出的日志格式
    dateformat: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5Level %logger{50} - %msg%n'
    # 在文件输出的日志格式
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} === [%thread] === %-5Level %logger{50} === %msg%n'

---
server:
  port: 8181
spring:
  profiles: dev

---
server:
  port: 8182
spring:
  profiles: prod

---
server:
  port: 8183
spring:
  profiles: test

---

#定义某些系统常量
person:
  name: 张三
  age: 18
  boss: false
  birth: 2020/11/11
  maps: {k1: v1,k2: v2}
  lists:
    - apple
    - banane
    - orange

