# yml中支持多模块环境配置，用 "---"分开即可
server:
  port: 8180
spring:
  profiles:
    active: dev
  # 数据源配置
  datasource:
    #url: jdbc:mysql://localhost:3306/kq?characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/kq?serverTimezone=UTC
    username: root
    password: root123
    # 指定数据源类型为druid
    type: com.alibaba.druid.pool.DruidDataSource

    # druid下的其他属性配置；需要另写配置文件才能生效，见DruidConfig类
    initialSize: 5 # 数据库连接池大小
    minIdle: 5
    maxActive: 50
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    maxEvictableIdleTimeMillis:  3000000 # 连接保持50分钟，单位是毫秒,因为公司防火墙长连接保持最长时间为1小时；此参数一定要结合实际情况进行配置。
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    #        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  # 邮件配置
  mail:
    username: ccc@qq.com
    password: bfnwlguvdbdlbeah #授权码
    host: smtp.qq.com
    #properties: mail.smtp.ssl.enable = true # 安全性设置

#  rabbitmq:
#    host: localhost
#    username: guest
#    password: guest

mybatis:
  # mapper映射文件位置
  mapper-locations: mapper/*.xml
  configuration:
    default-statement-timeout: 5

# 监控信息授权
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"


#logging:
#  # 打印的日志级别配置
#  level:
#    # 指明日志打印范围，不配置会报错
#    com.codebear: info
#  file:
#    # 在当前项目下生成spring boot.log日志，也可指定别的位置，如E:...（一般以配置下面的path为主）
#    #name: E:/springboot.log
#    # 在当前磁盘的根目录下创建spring文件夹和里面的log文件夹，使用spring.log作为默认文件
#    path: /spring/log
#  pattern:
#    # 在控制台输出的日志格式
#    dateformat: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5Level %logger{50} - %msg%n'
#    # 在文件输出的日志格式
#    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} === [%thread] === %-5Level %logger{50} === %msg%n'

# 打印项目运行期的具体日志，包含一些底层配置信息
# debug: true
---
server:
  port: 8181
spring:
  profiles: dev

---
server:
  port: 8182
spring:
  profiles: prod

---
server:
  port: 8183
spring:
  profiles: test

---

#定义某些系统常量
person:
  name: 张三
  age: 18
  boss: false
  birth: 2020/11/11
  maps: {k1: v1,k2: v2}
  lists:
    - apple
    - banane
    - orange

